name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Discord Embed
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK }}
          embed-title: ${{ github.event.release.name }}
          embed-url: https://github.com/chaospeach/Port/releases/download/${{ github.event.release.tag_name }}/Port.zip
          embed-description: ${{ github.event.release.body }}
          embed-color: 9442302

      - name: Update Homebrew Cask
        uses: macauley/action-homebrew-bump-cask@v1
        with:
          token: ${{secrets.BREW_TOKEN}}
          org: chaospeach
          cask: port-gaming
